name: Stable release 🕊️📦

on:
  release:
    types:
      - released
      - prereleased

jobs:
  docker:
    name: Build Docker images 💿💻
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v2.7.0

      - name: Configure QEMU ⚙️
        uses: docker/setup-qemu-action@v1.2.0

      - name: Configure Docker Buildx ⚙️
        uses: docker/setup-buildx-action@v1.7.0

      - name: Login to Docker Hub 🔑
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry 🔑
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.JF_BOT_TOKEN }}

      - name: Build and push stable images 🛠️⬆️
        if: github.event.action == 'released'
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm,linux/arm/v6
          build-args: |
            IS_STABLE=1
          tags: |
            jellyfin/jellyfin-vue:stable
            jellyfin/jellyfin-vue:stable.${{ github.event.release.tag_name }}
            jellyfin/jellyfin-vue:latest
            ghcr.io/jellyfin/jellyfin-vue:stable
            ghcr.io/jellyfin/jellyfin-vue:stable.${{ github.event.release.tag_name }}
            ghcr.io/jellyfin/jellyfin-vue:latest

      - name: Build and push release candidate images 🛠️⬆️
        if: github.event.action == 'prereleased'
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm,linux/arm/v6
          build-args: |
            IS_STABLE=1
          tags: |
            jellyfin/jellyfin-vue:stable-rc
            jellyfin/jellyfin-vue:stable-rc.${{ github.event.release.tag_name }}
            ghcr.io/jellyfin/jellyfin-vue:stable-rc
            ghcr.io/jellyfin/jellyfin-vue:stable-rc.${{ github.event.release.tag_name }}
