name: Unstable release 🪲📦

on:
  push:
    branches:
      - master

jobs:
  docker:
    name: Build Docker images 💿💻
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v2.7.0

      - name: Get current date ⌛
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Get commit hash ⚙️
        id: sha
        run: echo "::set-output name=sha::${GITHUB_SHA::7}"

      - name: Configure QEMU ⚙️
        uses: docker/setup-qemu-action@v1.2.0

      - name: Configure Docker Buildx ⚙️
        uses: docker/setup-buildx-action@v1.7.0

      - name: Login to Docker Hub 🔑
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry 🔑
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.JF_BOT_TOKEN }}

      - name: Build and push Docker images 🛠️
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm,linux/arm/v6
          tags: |
            jellyfin/jellyfin-vue:unstable
            jellyfin/jellyfin-vue:unstable.${{ steps.date.outputs.date }}.${{ steps.sha.outputs.sha }}
            ghcr.io/jellyfin/jellyfin-vue:unstable
            ghcr.io/jellyfin/jellyfin-vue:unstable.${{ steps.date.outputs.date }}.${{ steps.sha.outputs.sha }}
